name: Compile and run Fortran program

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install gfortran
        run: sudo apt-get install gfortran

      - name: Compile Fortran program
        run: gfortran hello_world.f90 -o hello_world

      - name: Run Fortran program
        run: ./hello_world

      - name: List directories
        run: ls